name: flutter_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.3.0
  go_router: ^12.1.0
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/logo/pikachu.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/pikachu.png"